### ISSUE TITLE
Autoplay doesn't continue after last episode of favorite show

### ISSUE THREAD

**Issue by a-Leong** [KorySchneider/wco-autoplay#1]
## Expected Behavior

When I reach the end of the last episode of my favorite anime, I want to continue watching. Additional episodes of the series should be generated and autoplayed in this case.

## Current Behavior

When I reach the end of the last episode, there is only silence. I see my reflection staring back.

## Steps to Reproduce

1. Open first episode of [Neon Genesis Evangelion](https://www.thewatchcartoononline.tv/anime/neon-genesis-evangelion-english-dubbed) in Chrome with wco-autoplay extension enabled
2. Play video and enjoy the pilot
3. Continue watching through the end of the series
4. Continue watching through the end of the movies
5. Feel the problem wash over you

## Context (Environment)

Version: 1.0
OS: macOS 11.5.2 (20G95)
Browser: Google Chrome 92.0.4515.159 (Official Build) (x86_64)

**Comment by KorySchneider** [comment]
[Congratulations!](https://www.youtube.com/watch?v=wDajqW561KM)

**Comment by a-Leong** [comment]
Thank you! That did the trick.
